# Generated by Django 6.0 on 2025-12-18 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tag',
            name='contacts',
            field=models.ManyToManyField(related_name='tags', to='contacts.contact'),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('user', 'phone_number', 'name')},
        ),
    ]
