# Generated by Django 6.0 on 2025-12-19 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='contacts',
        ),
        migrations.AddField(
            model_name='tag',
            name='contacts',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='contacts.contact'),
            preserve_default=False,
        ),
    ]
