# Generated by Django 6.0 on 2025-12-19 15:10

import apps.contacts.tests.check_phone_number
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_remove_tag_contacts_tag_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=13, validators=[apps.contacts.tests.check_phone_number.is_valid_phone_number]),
        ),
    ]
